
;; The build types are passed in from the build script (but can also be forced here)
;	DEFINE LowerROMBuild 1
;	DEFINE UpperROMBuild 1
;	DEFINE CartridgeBuild 1
;	DEFINE RAMBuild 1


;	DEFINE LowerRAMFailure #13
;	DEFINE UpperRAMFailure #61


	IFDEF LowerROMBuild
		DEFINE PAD_TO_16K
		DEFINE BUILD_STR 'L'
		DEFINE LOWER_RAM_TEST_START #4000
		DEFINE LOWER_RAM_TEST_SIZE  #C000
		DEFINE ROM_CHECK
		DEFINE PRINT_PROGRAM_SIZE
	ENDIF

	IFDEF UpperROMBuild
		DEFINE BUILD_STR 'U'
		DEFINE PAD_TO_16K
		DEFINE LOWER_RAM_TEST_START #0000
		DEFINE LOWER_RAM_TEST_SIZE  #C000
		DEFINE ROM_CHECK
	ENDIF

	IFDEF CartridgeBuild
		DEFINE PAD_TO_16K
		DEFINE BUILD_STR 'C'
		DEFINE LOWER_RAM_TEST_START #4000
		DEFINE LOWER_RAM_TEST_SIZE  #C000
	ENDIF

	IFDEF RAMBuild
		DEFINE BUILD_STR 'A'
		DEFINE LOWER_RAM_TEST_START #C000
		DEFINE LOWER_RAM_TEST_SIZE  #4000
		DEFINE ROM_CHECK
	ENDIF

	DEFINE VERSION_STR '0.4'
